# Generated by Django 5.2.7 on 2025-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='heading',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
