# Generated by Django 5.2.7 on 2025-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_heading_task_name_alter_task_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default='Not Completed'),
        ),
    ]
